/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-18-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public interface IUserBuilder  {

    void setFirstName();
    void setLastName();
    void setEmail();
    void setProfile();
    void setEmailEncodingKey();
    void setAlias();
    void setLanguageKey();
    void setLocalSIDkey();
    void setTimeZone();
    void setPermSets();
    void setUserName();
    User getuser();
    
}